/**
 * Chaînes par défaut (français) pour les apps Linux simulées.
 * Clés plates - surchargées par `content/strings.json` de la skin ou `CAPSULE_STRINGS_INLINE`.
 */
window.CAPSULE_STRINGS_DEFAULT = {
    'explorer.windowTitle': 'Fichiers',
    'firefox.windowTitle': 'Navigateur Web',
    'firefox.chromeAriaLabel': 'Interface navigateur',
    'firefox.tabsAriaLabel': 'Onglets',
    'firefox.tabNewLabel': 'Nouvel onglet',
    'firefox.tabNewButtonAria': 'Nouvel onglet',
    'firefox.toolbarAriaLabel': 'Barre de navigation',
    'firefox.backAria': 'Retour',
    'firefox.forwardAria': 'Avant',
    'firefox.reloadAria': 'Recharger',
    'firefox.addressLabel': 'Adresse',
    'firefox.addressPlaceholder': 'Rechercher avec Google ou saisir une adresse',
    'firefox.goAria': "Valider l'adresse",
    'firefox.goButton': 'Aller',
    'firefox.toolbarActionsAria': 'Actions navigateur',
    'firefox.homeAria': 'Accueil',
    'firefox.libraryAria': 'Bibliotheque',
    'firefox.bookmarksStarAria': 'Favoris',
    'firefox.menuAria': 'Menu',
    'firefox.profileAria': 'Profil Firefox',
    'firefox.pocketAria': 'Pocket',
    'firefox.bookmarkImportHint': 'Importer les marque-pages…',
    'firefox.newtabShortcutAliexpress': 'AliExpress',
    'firefox.newtabShortcutLeMonde': 'Le Monde',
    'firefox.newtabShortcutAdd': 'Ajouter un raccourci',
    'firefox.newtabShortcutAddAria': 'Ajouter un raccourci',
    'firefox.newtabSponsored': 'Sponsorisé',
    'firefox.newtabPocketTitle': 'Des articles qui font réfléchir',
    'firefox.newtabPocketArticle1Title': "InoCat, l'influenceuse sud-coréenne…",
    'firefox.newtabPocketArticle1Source': 'Madame Figaro',
    'firefox.newtabPocketArticle2Title': "Vassili Arkhipov, l'homme qui a sauvé l'humanité…",
    'firefox.newtabPocketArticle2Source': 'Le Point',
    'firefox.newtabPocketArticle3Title': '3 % de votre investissement reversés…',
    'firefox.newtabPocketArticle3Source': "Sponsorisé par CORUM L'Épargne",
    'firefox.statusProfileSoon': 'Profil Firefox : bientôt disponible.',
    'firefox.statusPocketSoon': 'Pocket : bientôt disponible.',
    'firefox.statusNewtabAddSoon': 'Ajout de raccourci : bientôt disponible.',
    'firefox.bookmarksBarAria': 'Favoris',
    'firefox.bookmarkHome': 'Accueil',
    'firefox.bookmarkImported': 'Importés',
    'firefox.bookmarkLocalhost': 'Localhost',
    'firefox.bookmarkLaCapsule': 'La Capsule',
    'firefox.bookmarkOsLaCapsule': 'os-lacapsule',
    'firefox.tabOsLaCapsuleLabel': 'La Capsule',
    'firefox.tabCloseAria': 'Fermer l’onglet',
    'firefox.newtabSearchLabel': 'Rechercher sur le Web',
    'firefox.newtabShortcutsAria': 'Raccourcis de la page d’accueil',
    'firefox.newtabShortcutWiki': 'Wikipédia',
    'firefox.newtabShortcutAmazon': 'Amazon',
    'firefox.newtabShortcutTemu': 'Temu',
    'firefox.newtabShortcutYoutube': 'YouTube',
    'firefox.newtabShortcutReddit': 'Reddit',
    'firefox.statusLibrarySoon': 'Bibliothèque : bientôt disponible.',
    'firefox.statusMenuSoon': 'Menu Firefox : bientôt disponible.',
    'firefox.statusNewtabShortcutSoon': 'Raccourci « {label} » : bientôt disponible.',
    'firefox.statusOsLaCapsuleLoading': 'Chargement de la page os-lacapsule...',
    'firefox.statusOsLaCapsuleShown': 'Page os-lacapsule affichee.',
    'firefox.statusWebLoading': 'Chargement de la page…',
    'firefox.statusWebShown': 'Page affichée.',
    'firefox.statusWebReloaded': 'Page rechargée.',
    'firefox.statusMntOpen': 'Ouverture du module pédagogique « {label} »…',
    'firefox.mntPanelLead': 'Module pédagogique « {module} » — parcours monté sous /mnt.',
    'firefox.mntPanelHint': 'Les Missions et les applications du scénario s\'ouvrent automatiquement si disponibles sur ce bureau.',
    'firefox.statusErrorWeb': "Erreur de chargement : impossible d'ouvrir la page.",
    'firefox.iframeOsLaCapsuleTitle': 'os-lacapsule',
    'firefox.statusSubmitRedirect': 'Toute saisie est redirigee vers os-lacapsule.',
    'firefox.statusHomeShown': 'Page Accueil affichee.',
    'firefox.statusHomeReloaded': 'Page Accueil rechargee.',
    'firefox.statusOsLaCapsuleReloaded': 'Page os-lacapsule rechargee.',
    'firefox.statusBackUnavailable': 'Retour indisponible pour le moment (mode simulation).',
    'firefox.statusForwardUnavailable': 'Avance indisponible pour le moment (mode simulation).',
    'firefox.statusNewTab': 'Nouvel onglet: page Accueil affichee.',
    'firefox.statusFavoriteHome': 'Favori "Accueil" ouvert.',
    'firefox.statusFavoriteOsLaCapsule': 'Favori « {label} » ouvert.',
    'firefox.statusBookmarkUnmapped': 'Favori « {label} » non mappe pour le moment.',
    'firefox.statusTabSimulated': 'Onglet « {label} » simule.',
    'firefox.statusErrorOsLaCapsule': "Erreur de chargement: impossible d'ouvrir la page os-lacapsule.",
    'firefox.siteLinuxMintTitle': 'Linux Mint',
    'firefox.siteLinuxMintLead': 'From freedom came elegance — linuxmint.com',
    'mainMenu.userName': 'capsule',
    'mainMenu.searchPlaceholder': 'Rechercher...',
    'profile.windowTitle': 'À Propos',
    'librewriter.windowTitle': 'Sans nom 1 - LibreOffice Writer',
    'librecalc.windowTitle': 'Sans nom 1 - LibreOffice Calc',
    'terminal.windowTitle': 'Terminal',
    'update_manager.windowTitle': 'Gestionnaire de mise à jour',
    'mintinstall.windowTitle': 'Logithèque',
    'system_monitor.windowTitle': 'Moniteur système',
    'baobab.windowTitle': 'Analyseur d\'espace disque',
    'webapp_manager.windowTitle': 'Applications Web',
    'sticky.windowTitle': 'Notes',
    'warpinator.windowTitle': 'Warpinator',
    'hypnotix.windowTitle': 'Hypnotix',
    'transmission.windowTitle': 'Transmission',
    'mintbackup.windowTitle': 'Outil de sauvegarde',
    'bulky.windowTitle': 'Renommer fichiers',
    'timeshift.windowTitle': 'Timeshift',
    'thunderbird.windowTitle': 'Thunderbird',
    'mintwelcome.windowTitle': 'Écran d\'accueil Mint',
    'gucharmap.windowTitle': 'Table de caractères',
    'simple_scan.windowTitle': 'Numérisation de documents',
    'thingy.windowTitle': 'Bibliothèque',
    'rhythmbox.windowTitle': 'Rhythmbox',
    'gnome_disks.windowTitle': 'Disques',
    'libreoffice_startcenter.windowTitle': 'LibreOffice',
    'libreoffice_draw.windowTitle': 'Sans nom 1 — LibreOffice Draw',
    'libreoffice_impress.windowTitle': 'Sans nom 1 — LibreOffice Impress',
    'mintstick.windowTitle': 'Créateur de clé USB',
    'mintstick_format.windowTitle': 'Formateur de clé USB',
    'font_viewer.windowTitle': 'Polices',
    'power_stats.windowTitle': 'Statistiques d\'alimentation',
    'mate_color_select.windowTitle': 'Sélecteur de couleur',
    'themes.windowTitle': 'Thèmes',
    'checklist.windowTitle': 'Missions',
    'checklist.description': 'Explore Linux Mint en accomplissant ces missions. Ta progression est sauvegardée.',
    'checklist.hint.open-nemo': 'Lance Nemo depuis la barre des tâches',
    'checklist.hint.open-menu': 'Clique sur le logo Mint en bas à gauche',
    'checklist.hint.open-profile': 'Ouvre le profil Linux Mint',
    'mainMenu.windowTitle': 'Menu',
    'visionneur_images.windowTitle': "Visionneur d'images",
    'visionneur_pdf.windowTitle': 'Visionneur PDF',
    'lecteur_multimedia.windowTitle': 'Lecteur multimédia',
    'calculator.windowTitle': 'Calculatrice',
    'screenshot.windowTitle': 'Capture d\'écran',
    'drawing.windowTitle': 'Sans titre — Dessin',
    'file_roller.windowTitle': 'Gestionnaire d\'archives',
    'mintdrivers.windowTitle': 'Gestionnaire de pilotes',
    'mintdrivers.lookingTitle': 'Recherche de pilotes',
    'mintdrivers.waitHint': 'Veuillez patienter…',
    'mintdrivers.noDriversTitle': 'Aucun pilote nécessaire',
    'mintdrivers.noDriversBody': 'Votre ordinateur n\'a besoin d\'aucun pilote supplémentaire.',
    'text_editor.windowTitle': 'Éditeur de texte',
    'clocks.windowTitle': 'Horloges',
    'calendar.windowTitle': 'Calendrier'
};
