/**
 * Chaînes par défaut (français) pour les apps Linux simulées.
 * Clés plates - surchargées par `content/strings.json` de la skin ou `CAPSULE_STRINGS_INLINE`.
 */
window.CAPSULE_STRINGS_DEFAULT = {
    'explorer.windowTitle': 'Fichiers',
    'firefox.windowTitle': 'Navigateur Web',
    'firefox.chromeAriaLabel': 'Interface navigateur',
    'firefox.tabsAriaLabel': 'Onglets',
    'firefox.tabNewLabel': 'Nouvel onglet',
    'firefox.tabNewButtonAria': 'Nouvel onglet',
    'firefox.toolbarAriaLabel': 'Barre de navigation',
    'firefox.backAria': 'Retour',
    'firefox.forwardAria': 'Avant',
    'firefox.reloadAria': 'Recharger',
    'firefox.addressLabel': 'Adresse',
    'firefox.addressPlaceholder': 'Rechercher avec Google ou saisir une adresse',
    'firefox.goAria': "Valider l'adresse",
    'firefox.goButton': 'Aller',
    'firefox.toolbarActionsAria': 'Actions navigateur',
    'firefox.homeAria': 'Accueil',
    'firefox.libraryAria': 'Bibliotheque',
    'firefox.bookmarksStarAria': 'Favoris',
    'firefox.menuAria': 'Menu',
    'firefox.bookmarksBarAria': 'Favoris',
    'firefox.bookmarkHome': 'Accueil',
    'firefox.bookmarkImported': 'Importés',
    'firefox.bookmarkLocalhost': 'Localhost',
    'firefox.bookmarkLaCapsule': 'La Capsule',
    'firefox.bookmarkOsLaCapsule': 'os-lacapsule',
    'firefox.tabOsLaCapsuleLabel': 'La Capsule',
    'firefox.tabCloseAria': 'Fermer l’onglet',
    'firefox.newtabSearchLabel': 'Rechercher sur le Web',
    'firefox.newtabShortcutsAria': 'Raccourcis de la page d’accueil',
    'firefox.newtabShortcutWiki': 'Wikipédia',
    'firefox.newtabShortcutYoutube': 'YouTube',
    'firefox.newtabShortcutReddit': 'Reddit',
    'firefox.newtabShortcutCapsule': 'La Capsule',
    'firefox.statusLibrarySoon': 'Bibliothèque : bientôt disponible.',
    'firefox.statusMenuSoon': 'Menu Firefox : bientôt disponible.',
    'firefox.statusNewtabShortcutSoon': 'Raccourci « {label} » : bientôt disponible.',
    'firefox.statusOsLaCapsuleLoading': 'Chargement de la page os-lacapsule...',
    'firefox.statusOsLaCapsuleShown': 'Page os-lacapsule affichee.',
    'firefox.iframeOsLaCapsuleTitle': 'os-lacapsule',
    'firefox.statusSubmitRedirect': 'Toute saisie est redirigee vers os-lacapsule.',
    'firefox.statusHomeShown': 'Page Accueil affichee.',
    'firefox.statusHomeReloaded': 'Page Accueil rechargee.',
    'firefox.statusOsLaCapsuleReloaded': 'Page os-lacapsule rechargee.',
    'firefox.statusBackUnavailable': 'Retour indisponible pour le moment (mode simulation).',
    'firefox.statusForwardUnavailable': 'Avance indisponible pour le moment (mode simulation).',
    'firefox.statusNewTab': 'Nouvel onglet: page Accueil affichee.',
    'firefox.statusFavoriteHome': 'Favori "Accueil" ouvert.',
    'firefox.statusFavoriteOsLaCapsule': 'Favori « {label} » ouvert.',
    'firefox.statusBookmarkUnmapped': 'Favori « {label} » non mappe pour le moment.',
    'firefox.statusTabSimulated': 'Onglet « {label} » simule.',
    'firefox.statusErrorOsLaCapsule': "Erreur de chargement: impossible d'ouvrir la page os-lacapsule.",
    'mainMenu.userName': 'capsule',
    'mainMenu.searchPlaceholder': 'Rechercher...',
    'profile.windowTitle': 'À Propos',
    'librewriter.windowTitle': 'Sans nom 1 - LibreOffice Writer',
    'librecalc.windowTitle': 'Sans nom 1 - LibreOffice Calc',
    'terminal.windowTitle': 'Terminal',
    'update_manager.windowTitle': 'Gestionnaire de mise à jour',
    'mintinstall.windowTitle': 'Logithèque',
    'themes.windowTitle': 'Thèmes',
    'checklist.windowTitle': 'Missions',
    'checklist.description': 'Explore Linux Mint en accomplissant ces missions. Ta progression est sauvegardée.',
    'checklist.hint.open-nemo': 'Lance Nemo depuis la barre des tâches',
    'checklist.hint.open-menu': 'Clique sur le logo Mint en bas à gauche',
    'checklist.hint.open-profile': 'Ouvre le profil Linux Mint',
    'mainMenu.windowTitle': 'Menu',
    'visionneur_images.windowTitle': "Visionneur d'images",
    'visionneur_pdf.windowTitle': 'Visionneur PDF',
    'lecteur_multimedia.windowTitle': 'Lecteur multimédia',
    'calculator.windowTitle': 'Calculatrice',
    'screenshot.windowTitle': 'Capture d\'écran',
    'drawing.windowTitle': 'Sans titre — Dessin',
    'file_roller.windowTitle': 'Gestionnaire d\'archives',
    'mintdrivers.windowTitle': 'Gestionnaire de pilotes',
    'mintdrivers.lookingTitle': 'Recherche de pilotes',
    'mintdrivers.waitHint': 'Veuillez patienter…',
    'mintdrivers.noDriversTitle': 'Aucun pilote nécessaire',
    'mintdrivers.noDriversBody': 'Votre ordinateur n\'a besoin d\'aucun pilote supplémentaire.',
    'text_editor.windowTitle': 'Éditeur de texte',
    'clocks.windowTitle': 'Horloges',
    'calendar.windowTitle': 'Calendrier'
};
